Insertion into DB with nickname and scores
WildCodeSchool/reims-0519-spring-bandersnatch pull request #16
Opened 2019-07-04 18:27 UTC by yagerdev

2019-07-05 07:26 UTC, rocambille requested changes

2019-07-05 07:26 UTC, rocambille commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +    int currentScores = 0;
l'attribut représente un seul score, le score courant : à mettre au singulier

2019-07-05 07:26 UTC, rocambille commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
> +/home/wilder/Documents/Projet2/java_bandersnatch/reims-0519-spring-bandersnatch/src/test/java/com/wildcodeschool/bandersnatch/BandersnatchApplicationTests.java
à supprimer de la PR

2019-07-05 08:37 UTC, rocambille requested changes

2019-07-05 08:37 UTC, rocambille commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/PageController.java
> +
ce n'est pas une vrai modif : à enlever

2019-07-05 08:37 UTC, rocambille commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/ScoreController.java
> +}
ce n'est pas une vrai modif : à enlever

2019-07-05 08:37 UTC, rocambille commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
> +/home/wilder/Documents/Projet2/java_bandersnatch/reims-0519-spring-bandersnatch/src/test/java/com/wildcodeschool/bandersnatch/BandersnatchApplicationTests.java
c'est toujours là : à supprimer

2019-07-05 09:01 UTC, yagerdev reviewed
reviewed

2019-07-08 07:19 UTC, rocambille requested changes

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +    int currentScore = 0;
ça fait un score créé par instance du contrôleur : sûr que ça fait un et un seul score sur une partie ? à stocker dans la session plutôt, comme pour le pseudo

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +                    currentScore++;
incrémente le score dans tous les cas, ce sera plus simple ;)

même si ça veut dire partir du principe que l'id de la pièce courante et l'action sont des entrées valides

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +        model.addAttribute("currentScores", session.getAttribute("currentScores"));
currentScores -> currentScore

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +            session.setAttribute("currentScores", currentScore);
currentScores -> currentScore

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
>              // "<form action='/game' method='post'><input name='action' value='lose'><button class='btn btn-primary my-1'>Get out of prison!</button></form>";
code mort : à supprimer

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/PageController.java
> +}
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/ScoreController.java
> +
fausse modif : à supprimer de la PR

2019-07-08 07:19 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/ScoreController.java
> +}
fausse modif : à supprimer de la PR

2019-07-08 08:25 UTC, rocambille requested changes

2019-07-08 08:25 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/PageController.java
> +<<<<<<< HEAD
artefact de conflit

2019-07-08 08:39 UTC, yagerdev reviewed
ok

2019-07-08 09:13 UTC, rocambille requested changes

2019-07-08 09:13 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +    int currentScore = 0;
à supprimer

2019-07-08 09:13 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +            session.setAttribute("currentScore", currentScore);
initialiser avec 0

2019-07-08 09:13 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +            currentScore++;
modifier le contenu de la session

2019-07-08 09:13 UTC, wasthishelpful commented on src/main/resources/templates/scores.html
> +        <p class="card-text"><strong th:text="${currentScores}">Scores is  <!-- texte ici--> :</strong><br> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis imperdiet massa, ut t
toujours cohérent avec le controleur ?

2019-07-08 09:13 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/entities/Score.java
> +        this.user_score = user_score;
à modifier pour respecter les conventions java : camelCase. attribut + nom de méthode

2019-07-09 08:14 UTC, closed without merging