Createpathroom
WildCodeSchool/reims-0519-spring-bandersnatch pull request #17
Opened 2019-07-05 09:16 UTC by Seb-Dupuis

2019-07-05 09:40 UTC, rocambille requested changes

2019-07-05 09:40 UTC, rocambille commented on src/main/java/com/wildcodeschool/bandersnatch/repositories/RoomRepository.java
> +
pourquoi des sauts de lignes ont été ajoutés ? ils ne sont pas utiles, et risquent de provoquer des conflits

2019-07-05 12:04 UTC, Seb-Dupuis commented on src/main/java/com/wildcodeschool/bandersnatch/repositories/RoomRepository.java
> +
C'est du a un copier/coller aprioris. Je me suis dis que c'était pas grave, j'ai pas pensé à ça en effet, je ferais attention  à l'avenir merci

2019-07-08 08:11 UTC, rocambille requested changes

2019-07-08 08:11 UTC, rocambille commented on src/main/java/com/wildcodeschool/bandersnatch/repositories/RoomRepository.java
> +
en attendant l'avenir, c'est à nettoyer :)

2019-07-08 08:24 UTC, merged