Get score
WildCodeSchool/reims-0519-spring-bandersnatch pull request #19
Opened 2019-07-08 13:27 UTC by yagerdev

2019-07-08 14:08 UTC, rocambille requested changes

2019-07-08 14:08 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/BandersnatchApplication.java
> +import com.wildcodeschool.bandersnatch.repositories.ScoreRepository;
ScoreRepository n'est pas utilisé dans l'application (ce qui est normal), mais du coup l'import n'a rien à faire là

2019-07-08 14:08 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/BandersnatchApplication.java
> +		SpringApplication.run(BandersnatchApplication.class, args);
rajouter des espaces à la fin d'une ligne : modif à supprimer

2019-07-08 14:08 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +    int currentScore = 0;
toujours à supprimer

2019-07-08 14:08 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +            currentScore++;
le score de l'utilisateur est stocké dans la session (cf. ligne 108) : c'est celui là qu'il faut modifier

2019-07-08 14:08 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/ScoreController.java
> +        return ScoreRepository.selectScores();
pourquoi pas, mais qu'est-ce qu'un repository de score pourrait sélectionner d'autres que des scores ?

2019-07-09 08:06 UTC, yagerdev commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +    int currentScore = 0;
corrigé

2019-07-09 08:10 UTC, yagerdev reviewed
reviewed

2019-07-09 08:25 UTC, closed without merging