finalisation css
WildCodeSchool/reims-0519-spring-bandersnatch pull request #20
Opened 2019-07-08 14:54 UTC by Seb-Dupuis

2019-07-08 15:40 UTC, wasthishelpful commented
conflits à résoudre :/

2019-07-09 06:53 UTC, Seb-Dupuis commented
> conflits à résoudre :/

C'est réglé :)

2019-07-09 07:32 UTC, rocambille requested changes

2019-07-09 07:32 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +                    return "gamewin";
ça veut dire que je gagne sur la room 6 ? ça casse les modifs de Vincent, non ?

2019-07-09 07:32 UTC, wasthishelpful commented on src/main/java/com/wildcodeschool/bandersnatch/controllers/GameController.java
> +
à supprimer de la PR

2019-07-09 09:05 UTC, merged